Server configuration, Stack Arena and Update Makefile
TeaInside/teavpn2 pull request #8
Opened 2020-09-29 15:00 UTC by ammarfaizi2

1. Server configuration (argv parser and config ini parser).
2. Stack arena (allocate huge area of stack for future dynamic memory allocation).
3. Update Makefile (addressing this discussion: https://t.me/TeaInside/34245 and some improvements).

2020-09-29 15:16 UTC, louvian requested changes
We need to talk in detail :)
I postpone the further review.

2020-09-29 15:16 UTC, louvian commented on src/sources/teavpn2/global/memory.c
> +#else
Can you create unit tests for this macro?
That looks horrible to me.

2020-09-29 15:16 UTC, louvian commented on src/sources/teavpn2/server/config.c
> +  } else {
Incomplete config parser?

2020-09-29 15:16 UTC, louvian commented on Makefile
>  NASM   = nasm
Why do we need NASM here?

2020-09-29 15:16 UTC, louvian commented on src/sources/teavpn2/server/config.c
> +      targ[2] = (targ[2] >= 'A' && targ[2] <= 'Z') ? targ[2] + 32 : targ[2];
Please explain why don't you use `tolower()` from standard library?

2020-09-29 15:25 UTC, ammarfaizi2 commented on src/sources/teavpn2/server/config.c
> +      targ[2] = (targ[2] >= 'A' && targ[2] <= 'Z') ? targ[2] + 32 : targ[2];
I haven't examined the Assembly, but I think it reduces call overhead by performing those tolower manual arithmetic.

2020-09-29 15:26 UTC, ammarfaizi2 commented on Makefile
>  NASM   = nasm
It is for future support, currently we have no NASM source code.

2020-09-29 15:27 UTC, ammarfaizi2 commented on src/sources/teavpn2/server/config.c
> +  } else {
Yes, I am still fixing it.

2020-09-29 15:28 UTC, ammarfaizi2 commented on src/sources/teavpn2/global/memory.c
> +#else
Yes, I will be back to you later today.

2020-09-29 16:14 UTC, zeheater commented on src/sources/teavpn2/global/memory.c
> +}
I don't understand what this function allocate, can you explain more ?

2020-09-30 00:21 UTC, ammarfaizi2 commented on src/sources/teavpn2/global/memory.c
> +}
Yes, it is customized memory allocation. I am going to write the detailed technical about this together with its unit tests soon.

2020-09-30 00:24 UTC, ammarfaizi2 commented on src/sources/teavpn2/server/config.c
> +  } else {
Resolved

2020-10-01 05:14 UTC, ammarfaizi2 commented
@louvian below is the examined situation about `tolower()` consideration.

## Standard tolower() with optimization (-O3)
`tolower()` calls `__ctype_tolower_loc@plt`. 
```
gef➤  r
`/home/ammarfaizi2/project/now/teavpn2/teavpn_server' has changed; re-reading symbols.
Starting program: /home/ammarfaizi2/project/now/teavpn2/teavpn_server ./teavpn_server -c config/server.ini
warning: Probes-based dynamic linker interface failed.
Reverting to original interface.
Parsing arguments...
  config->config_file = "config/server.ini"

Breakpoint 4, server_parser_handler (user=user@entry=0x7fffffffcf60, section=<optimized out>, name=<optimized out>, value=0x7fffffffccfc "tcp", lineno=<optimized out>) at src/sources/teavpn2/server/config.c:75
75	      targ[0] = tolower(targ[0]);
[ Legend: Modified register | Code | Heap | Stack | String ]
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── registers ────
$rax   : 0x00007fffffffcbe4  →  0xfcd0f40000706374 ("tcp"?)
$rbx   : 0x00007fffffffcf60  →  0x00007fffffffe43c  →  "config/server.ini"
$rcx   : 0x00007fffffffcbe7  →  0x8298acfcd0f40000
$rdx   : 0x00007fffffffcbe4  →  0xfcd0f40000706374 ("tcp"?)
$rsp   : 0x00007fffffffcbe0  →  0x00706374f7f5b3c0
$rbp   : 0x00007fffffffccfc  →  0x0000000000706374 ("tcp"?)
$rsi   : 0x00007fffffffccfc  →  0x0000000000706374 ("tcp"?)
$rdi   : 0x00007fffffffcbe4  →  0xfcd0f40000706374 ("tcp"?)
$rip   : 0x0000555555555c35  →  <server_parser_handler+757> call 0x555555555180 <__ctype_tolower_loc@plt>
$r8    : 0x0               
$r9    : 0x00007fffffffcc70  →  0x000074656b636f73 ("socket"?)
$r10   : 0x00007ffff7f5aac0  →  0x0000000100000000
$r11   : 0x7079745f6b636f73 ("sock_typ"?)
$r12   : 0x0               
$r13   : 0x00007fffffffcbe4  →  0xfcd0f40000706374 ("tcp"?)
$r14   : 0x00007fffffffccf0  →  "sock_type"
$r15   : 0x00007ffff7f5b3c0  →  0x0002000200020002
$eflags: [ZERO carry PARITY adjust sign trap INTERRUPT direction overflow resume virtualx86 identification]
$cs: 0x0033 $ss: 0x002b $ds: 0x0000 $es: 0x0000 $fs: 0x0000 $gs: 0x0000 
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── stack ────
0x00007fffffffcbe0│+0x0000: 0x00706374f7f5b3c0	 ← $rsp
0x00007fffffffcbe8│+0x0008: 0x778298acfcd0f400
0x00007fffffffcbf0│+0x0010: 0x00007fffffffd310  →  0x0000000000000000
0x00007fffffffcbf8│+0x0018: 0x00007fffffffccfe  →  0x2e00000000000070 ("p"?)
0x00007fffffffcc00│+0x0020: 0x00007fffffffcf20  →  0x000055555555a6b0  →  0x00000000fbad2488
0x00007fffffffcc08│+0x0028: 0x000000000000000b
0x00007fffffffcc10│+0x0030: 0x00007fffffffccf0  →  "sock_type"
0x00007fffffffcc18│+0x0038: 0x0000555555555f61  →  <ini_parse_stream+481> mov ecx, DWORD PTR [rsp+0x3c]
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── code:x86:64 ────
   0x555555555c2a <server_parser_handler+746> mov    rsi, rbp
   0x555555555c2d <server_parser_handler+749> mov    rdi, r13
   0x555555555c30 <server_parser_handler+752> call   0x5555555550f0 <strncpy@plt>
 → 0x555555555c35 <server_parser_handler+757> call   0x555555555180 <__ctype_tolower_loc@plt>
   ↳  0x555555555180 <__ctype_tolower_loc@plt+0> endbr64 
      0x555555555184 <__ctype_tolower_loc@plt+4> bnd    jmp QWORD PTR [rip+0x3e25]        # 0x555555558fb0 <__ctype_tolower_loc@got.plt>
      0x55555555518b <__ctype_tolower_loc@plt+11> nop    DWORD PTR [rax+rax*1+0x0]
      0x555555555190 <__ctype_b_loc@plt+0> endbr64 
      0x555555555194 <__ctype_b_loc@plt+4> bnd    jmp QWORD PTR [rip+0x3e1d]        # 0x555555558fb8 <__ctype_b_loc@got.plt>
      0x55555555519b <__ctype_b_loc@plt+11> nop    DWORD PTR [rax+rax*1+0x0]
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── arguments (guessed) ────
__ctype_tolower_loc@plt (
)
──────────────────────────────────────────────────────────────────────────────────────────────────────────────── source:src/sources/tea[...].c+75 ────
     70	 
     71	       strncpy(targ, value, 3);
     72	       // targ[0] = (targ[0] >= 'A' && targ[0] <= 'Z') ? targ[0] + 32 : targ[0];
     73	       // targ[1] = (targ[1] >= 'A' && targ[1] <= 'Z') ? targ[1] + 32 : targ[1];
     74	       // targ[2] = (targ[2] >= 'A' && targ[2] <= 'Z') ? targ[2] + 32 : targ[2];
               // targ=0x00007fffffffcbe4  →  0xfcd0f40000706374 ("tcp"?)
 →   75	       targ[0] = tolower(targ[0]);
     76	       targ[1] = tolower(targ[1]);
     77	       targ[2] = tolower(targ[2]);
     78	       targ[3] = '\0';
     79	 
     80	       if (!strcmp(targ, "tcp")) {
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── threads ────
[#0] Id 1, Name: "teavpn_server", stopped, reason: BREAKPOINT
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── trace ────
[#0] 0x555555555c35 → server_parser_handler(user=0x7fffffffcf60, section=<optimized out>, name=<optimized out>, value=0x7fffffffccfc "tcp", lineno=<optimized out>)
[#1] 0x555555555f61 → ini_parse_stream(reader=0x7ffff7e417b0, stream=0x55555555a6b0, handler=0x555555555940 <server_parser_handler>, user=0x7fffffffcf60)
[#2] 0x5555555563b9 → ini_parse_file(file=0x55555555a6b0, handler=0x555555555940 <server_parser_handler>, user=0x7fffffffcf60)
[#3] 0x5555555563f1 → ini_parse(filename=<optimized out>, handler=0x555555555940 <server_parser_handler>, user=0x7fffffffcf60)
[#4] 0x555555555cf7 → tvpn_server_load_config_file(file=<optimized out>, config=0x7fffffffcf60)
[#5] 0x555555555223 → main(argc=0x4, argv=0x7fffffffe0d8, envp=0x7fffffffe100)
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
gef➤ 
```

## Customized tolower() with optimization (-O3)
We have no call to function to do tolower().
```
gef➤  r
Starting program: /home/ammarfaizi2/project/now/teavpn2/teavpn_server -c config/server.ini
Parsing arguments...
  config->config_file = "config/server.ini"

Breakpoint 2, server_parser_handler (user=user@entry=0x7fffffffcf70, section=<optimized out>, name=<optimized out>, value=0x7fffffffcd0c "tcp", lineno=<optimized out>) at src/sources/teavpn2/server/config.c:72
72	      targ[0] = (targ[0] >= 'A' && targ[0] <= 'Z') ? targ[0] + 32 : targ[0];
[ Legend: Modified register | Code | Heap | Stack | String ]
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── registers ────
$rax   : 0x00007fffffffcc04  →  0x1eaadd0000706374 ("tcp"?)
$rbx   : 0x00007fffffffcf70  →  0x00007fffffffe43c  →  "config/server.ini"
$rcx   : 0x00007fffffffcc07  →  0x8d38211eaadd0000
$rdx   : 0x00007fffffffcc04  →  0x1eaadd0000706374 ("tcp"?)
$rsp   : 0x00007fffffffcc00  →  0x00706374ffffd320
$rbp   : 0x00007fffffffcd0c  →  0x0000000000706374 ("tcp"?)
$rsi   : 0x00007fffffffcd0c  →  0x0000000000706374 ("tcp"?)
$rdi   : 0x0000555555557004  →  0x0070647500706374 ("tcp"?)
$rip   : 0x0000555555555c14  →  <server_parser_handler+756> movzx eax, BYTE PTR [rsp+0x4]
$r8    : 0x00007fffffffcc04  →  0x1eaadd0000706374 ("tcp"?)
$r9    : 0x00007fffffffcc80  →  0x000074656b636f73 ("socket"?)
$r10   : 0x00007ffff7f5aac0  →  0x0000000100000000
$r11   : 0x7079745f6b636f73 ("sock_typ"?)
$r12   : 0x0               
$r13   : 0x00007fffffffcd00  →  "sock_type"
$r14   : 0x00007fffffffcd00  →  "sock_type"
$r15   : 0x00007ffff7f5b3c0  →  0x0002000200020002
$eflags: [ZERO carry PARITY adjust sign trap INTERRUPT direction overflow resume virtualx86 identification]
$cs: 0x0033 $ss: 0x002b $ds: 0x0000 $es: 0x0000 $fs: 0x0000 $gs: 0x0000 
─────────────────────────────────────────────────────────────────────────────────────────── [...]

2020-10-01 05:23 UTC, ammarfaizi2 commented on src/sources/teavpn2/global/memory.c
> +#else
The unit tests have been created https://github.com/TeaInside/teavpn2/pull/8/commits/d87f66acbda58ede0d88540b866feeb7213f0372

2020-10-01 05:24 UTC, ammarfaizi2 commented on src/sources/teavpn2/server/config.c
> +      targ[2] = (targ[2] >= 'A' && targ[2] <= 'Z') ? targ[2] + 32 : targ[2];
Can we resolve this tolower problem now?

2020-10-01 05:36 UTC, louvian commented
I think there is nothing wrong with this `tolower()`, let's go for it!

On Thu, Oct 1, 2020 at 12:14 PM Ammar Faizi <notifications@github.com>
wrote:

> @louvian <https://github.com/louvian> below is the examined situation
> about tolower() consideration.
> Standard tolower() with optimization (-O3)
>
> tolower() calls __ctype_tolower_loc@plt.
>
> gef➤  r
> `/home/ammarfaizi2/project/now/teavpn2/teavpn_server' has changed; re-reading symbols.
> Starting program: /home/ammarfaizi2/project/now/teavpn2/teavpn_server ./teavpn_server -c config/server.ini
> warning: Probes-based dynamic linker interface failed.
> Reverting to original interface.
> Parsing arguments...
>   config->config_file = "config/server.ini"
>
> Breakpoint 4, server_parser_handler (user=user@entry=0x7fffffffcf60, section=<optimized out>, name=<optimized out>, value=0x7fffffffccfc "tcp", lineno=<optimized out>) at src/sources/teavpn2/server/config.c:75
> 75	      targ[0] = tolower(targ[0]);
> [ Legend: Modified register | Code | Heap | Stack | String ]
> ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── registers ────
> $rax   : 0x00007fffffffcbe4  →  0xfcd0f40000706374 ("tcp"?)
> $rbx   : 0x00007fffffffcf60  →  0x00007fffffffe43c  →  "config/server.ini"
> $rcx   : 0x00007fffffffcbe7  →  0x8298acfcd0f40000
> $rdx   : 0x00007fffffffcbe4  →  0xfcd0f40000706374 ("tcp"?)
> $rsp   : 0x00007fffffffcbe0  →  0x00706374f7f5b3c0
> $rbp   : 0x00007fffffffccfc  →  0x0000000000706374 ("tcp"?)
> $rsi   : 0x00007fffffffccfc  →  0x0000000000706374 ("tcp"?)
> $rdi   : 0x00007fffffffcbe4  →  0xfcd0f40000706374 ("tcp"?)
> $rip   : 0x0000555555555c35  →  <server_parser_handler+757> call 0x555555555180 <__ctype_tolower_loc@plt>
> $r8    : 0x0
> $r9    : 0x00007fffffffcc70  →  0x000074656b636f73 ("socket"?)
> $r10   : 0x00007ffff7f5aac0  →  0x0000000100000000
> $r11   : 0x7079745f6b636f73 ("sock_typ"?)
> $r12   : 0x0
> $r13   : 0x00007fffffffcbe4  →  0xfcd0f40000706374 ("tcp"?)
> $r14   : 0x00007fffffffccf0  →  "sock_type"
> $r15   : 0x00007ffff7f5b3c0  →  0x0002000200020002
> $eflags: [ZERO carry PARITY adjust sign trap INTERRUPT direction overflow resume virtualx86 identification]
> $cs: 0x0033 $ss: 0x002b $ds: 0x0000 $es: 0x0000 $fs: 0x0000 $gs: 0x0000
> ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── stack ────
> 0x00007fffffffcbe0│+0x0000: 0x00706374f7f5b3c0	 ← $rsp
> 0x00007fffffffcbe8│+0x0008: 0x778298acfcd0f400
> 0x00007fffffffcbf0│+0x0010: 0x00007fffffffd310  →  0x0000000000000000
> 0x00007fffffffcbf8│+0x0018: 0x00007fffffffccfe  →  0x2e00000000000070 ("p"?)
> 0x00007fffffffcc00│+0x0020: 0x00007fffffffcf20  →  0x000055555555a6b0  →  0x00000000fbad2488
> 0x00007fffffffcc08│+0x0028: 0x000000000000000b
> 0x00007fffffffcc10│+0x0030: 0x00007fffffffccf0  →  "sock_type"
> 0x00007fffffffcc18│+0x0038: 0x0000555555555f61  →  <ini_parse_stream+481> mov ecx, DWORD PTR [rsp+0x3c]
> ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── code:x86:64 ────
>    0x555555555c2a <server_parser_handler+746> mov    rsi, rbp
>    0x555555555c2d <server_parser_handler+749> mov    rdi, r13
>    0x555555555c30 <server_parser_handler+752> call   0x5555555550f0 <strncpy@plt>
>  → 0x555555555c35 <server_parser_handler+757> call   0x555555555180 <__ctype_tolower_loc@plt>
>    ↳  0x555555555180 <__ctype_tolower_loc@plt+0> endbr64
>       0x555555555184 <__ctype_tolower_loc@plt+4> bnd    jmp QWORD PTR [rip+0x3e25]        # 0x555555558fb0 <__ctype_tolower_loc@got.plt>
>       0x55555555518b <__ctype_tolower_loc@plt+11> nop    DWORD PTR [rax+rax*1+0x0]
>       0x555555555190 <__ctype_b_loc@plt+0> endbr64
>       0x555555555194 <__ctype_b_loc@plt+4> bnd    jmp QWORD PTR [rip+0x3e1d]        # 0x555555558fb8 <__ctype_b_loc@got.plt>
>       0x55555555519b <__ctype_b_loc@plt+11> nop    DWORD PTR [rax+rax*1+0x0]
> ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── arguments (guessed) ────
> __ctype_tolower_loc@plt (
> )
> ──────────────────────────────────────────────────────────────────────────────────────────────────────────────── source:src/sources/tea[...].c+75 ────
>      70	
>      71	       strncpy(targ, value, 3);
>      72	       // targ[0] = (targ[0] >= 'A' && targ[0] <= 'Z') ? targ[0] + 32 : targ[0];
>      73	       // targ[1] = (targ[1] >= 'A' && targ[1] <= 'Z') ? targ[1] + 32 : targ[1];
>      74	       // targ[2] = (targ[2] >= 'A' && targ[2] <= 'Z') ? targ[2] + 32 : targ[2];
>                // targ=0x00007fffffffcbe4  →  0xfcd0f40000706374 ("tcp"?)
>  →   75	       targ[0] = tolower(targ[0]);
>      76	       targ[1] = tolower(targ[1]);
>      77	       targ[2] = tolower(targ[2]);
>      78	       targ[3] = '\0';
>      79	
>      80	       if (!strcmp(targ, "tcp")) {
> ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── threads ────
> [#0] Id 1, Name: "teavpn_server", stopped, reason: BREAKPOINT
> ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── trace ────
> [#0] 0x555555555c35 → server_parser_handler(user=0x7fffffffcf60, section=<optimized out>, name=<optimized out>, value=0x7fffffffccfc "tcp", lineno=<optimized out>)
> [#1] 0x555555555f61 → ini_parse_stream(reader=0x7ffff7e417b0, stream=0x55555555a6b0, handler=0x555555555940 <server_parser_handler>, user=0x7fffffffcf60)
> [#2] 0x5555555563b9 → ini_parse_file(file=0x55555555a6b0, handler=0x555555555940 <server_parser_handler>, user=0x7fffffffcf60)
> [#3] 0x5555555563f1 → ini_parse(filename=<optimized out>, handler=0x555555555940 <server_parser_handler>, user=0x7fffffffcf60)
> [#4] 0x555555555cf7 → tvpn_server_load_config_file(file=<optimized out>, config=0x7fffffffcf60)
> [#5] 0x555555555223 → main(argc=0x4, argv=0x7fffffffe0d8, envp=0x7fffffffe100)
> ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> gef➤
>
> Customized tolower() with optimization (-O3)
>
> We have no call to function to do tolower().
>
> gef➤  r
> Starting program: /home/ammarfaizi2/project/now/teavpn2/teavpn_server -c config/server.ini
> Parsing arguments...
>   config->config_file = "config/server.ini"
>
> Breakpoint 2, server_parser_handler (user=user@entry=0x7fffffffcf70, section=<optimized out>, name=<optimized out>, value=0x7fffffffcd0c "tcp", lineno=<optimized out>) at src/sources/teavpn2/server/config.c:72
> 72	      targ[0] = (targ[0] >= 'A' && targ[0] <= 'Z') ? targ[0] + 32 : targ[0];
> [ Legend: Modified register | Code | Heap | Stack | String ]
> ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── registers ────
> $rax   : 0x00007fffffffcc04  →  0x1eaadd0000706374 ("tcp"?)
> $rbx   : 0x00007fffffffcf70  →  0x00007fffffffe43c  →  "config/server.ini"
> $rcx   : 0x00007fffffffcc07  →  0x8d38211eaadd0000
> $rdx   : 0x00007fffffffcc04  →  0x1eaadd0000706374 ("tcp"?)
> $rsp   : 0x00007fffffffcc00  →  0x00706374ffffd320
> $rbp   : 0x00007fffffffcd0c  →  0x0000000000706374 ("tcp"?)
> $rsi   : 0x00007fffffffcd0c  →  0x0000000000706374 ("tcp"?)
> $rdi   : 0x0000555555557004  →  0x0070647500706374 ("tcp"?)
> $rip   : 0x0000555555555c14  →  <server_parser_handler+756> movzx eax, BYTE PTR [rsp+0x4]
> $r8    : 0x00007fffffffcc04  →  0x1eaadd0000706374 ("tcp"?)
> $r9    : 0x00007fffffffcc80  →  0x000074656b636f73 ("socket"?)
> $r10   : 0x00007ffff7f5aac0  →  0x0000000100000000
> $r11   : 0x7079745f6b636f73 ("sock_typ"?)
> $r12   : 0x0
> $r13   : 0x00007fffffffcd00  →  "sock_type"
> $r14   : 0x00007fffffffcd00  →  "sock_t [...]

2020-10-01 05:38 UTC, louvian commented
@ammarfaizi2 is this ready for re-review?

2020-10-01 05:39 UTC, Sunda001 commented
@louvian interesting

2020-10-01 05:42 UTC, ammarfaizi2 commented
@louvian Yes, we it seems it is ready for re-review.
Cc: @zeheater

2020-10-01 05:46 UTC, ammarfaizi2 commented
@louvian I am going to add CI in the near future before this PR be merged. So please don't merge it in case you approve the latest changes.

Cc: @zeheater

2020-10-01 06:52 UTC, louvian commented on Makefile
> +DEFAULT_OPTIMIZATION = -O3
Are you sure `-O3` as default optimization?

2020-10-01 07:16 UTC, louvian requested changes

2020-10-01 07:16 UTC, louvian commented on src/sources/teavpn2/global/third_party/inih/inih.c
> +#endif
Is this a warning supression?

2020-10-01 07:16 UTC, louvian commented on src/sources/teavpn2/server/config.c
> +      targ[2] = (targ[2] >= 'A' && targ[2] <= 'Z') ? targ[2] + 32 : targ[2];
Resolved

2020-10-01 07:16 UTC, louvian commented on tests/test.mk
> +BIN_DIR			   = .bin
Too many spaces or tabs, keep them inline so it looks better.

2020-10-01 07:16 UTC, louvian commented on src/sources/teavpn2/server/config.c
> +      // targ[2] = tolower(targ[2]);
You can remove this

2020-10-01 07:16 UTC, louvian commented on src/sources/teavpn2/server/argv_parser.c
> +  printf("  -m, --mtu=MTU\t\t\tSet mtu value (default: %d).\n", default_mtu);
Maybe add `--version` option?

2020-10-01 07:16 UTC, louvian commented on src/sources/teavpn2/server/config.c
> +}
It can be simplified in one line

2020-10-01 07:16 UTC, louvian commented on tests/Makefile
> +SOURCES   = $(shell find ${TARGET_TEST} -name '*.c')
No C++ support for unit tests?

2020-10-01 07:16 UTC, louvian commented on .github/workflows/c-cpp.yml
> +        path: teavpn_server
Why don't you store `teavpn_client` too?

2020-10-01 07:16 UTC, louvian commented on .github/workflows/c-cpp.yml
> +          - { target: g++-5, compiler: g++, cxx-version: 5.5.0 }
Isn't it overkill to support these many compilers?
I would like to build on different machine instead different compiler in the same machine.
However, we can take severals gcc and clang in the same machine, but don't be this many.

2020-10-01 07:16 UTC, louvian commented on Makefile
>  NASM   = nasm
I don't know why we need NASM when GAS exists.

2020-10-01 10:22 UTC, ammarfaizi2 commented on Makefile
> +DEFAULT_OPTIMIZATION = -O3
Resolved, changed to `-O0`.

2020-10-01 10:22 UTC, ammarfaizi2 commented on src/sources/teavpn2/global/third_party/inih/inih.c
> +#endif
Yes, it is.

2020-10-01 10:23 UTC, ammarfaizi2 commented on tests/test.mk
> +BIN_DIR			   = .bin
Resolved.

2020-10-01 10:24 UTC, ammarfaizi2 commented on src/sources/teavpn2/server/argv_parser.c
> +  printf("  -m, --mtu=MTU\t\t\tSet mtu value (default: %d).\n", default_mtu);
Not really important for now.

2020-10-01 10:25 UTC, ammarfaizi2 commented on src/sources/teavpn2/server/config.c
> +      // targ[2] = tolower(targ[2]);
Resolved.

2020-10-01 10:26 UTC, ammarfaizi2 commented on tests/Makefile
> +SOURCES   = $(shell find ${TARGET_TEST} -name '*.c')
Currently, no need to add C++ support for unit tests.

2020-10-01 10:28 UTC, ammarfaizi2 commented on src/sources/teavpn2/server/config.c
> +}
Resolved.

2020-10-01 10:28 UTC, ammarfaizi2 commented on .github/workflows/c-cpp.yml
> +        path: teavpn_server
Resolved.

2020-10-01 10:28 UTC, ammarfaizi2 commented on .github/workflows/c-cpp.yml
> +          - { target: g++-5, compiler: g++, cxx-version: 5.5.0 }
Resolved.

2020-10-01 10:29 UTC, ammarfaizi2 commented on Makefile
>  NASM   = nasm
We can discuss it later. It think it is not really important for now.

2020-10-01 10:30 UTC, ammarfaizi2 commented
Requested changes are all resolved, please re-review @louvian.

2020-10-01 10:34 UTC, ammarfaizi2 commented
Forgot to push the latest changes, should be ok now.

2020-10-01 13:11 UTC, zeheater approved these changes
Looks good

2020-10-01 14:57 UTC, louvian approved these changes
Good, ready to merge :)

2020-10-01 15:00 UTC, louvian commented
Note before merge @ammarfaizi2:
We will have to make the internal documentation that explains the custom mechanism like allocator and memcpy in the above commits (in the next PR maybe), hope it can be achieved while hacktoberfest is still going.

2020-10-01 15:16 UTC, ammarfaizi2 commented
@louvian yes, I am responsible for that work. Will do that soon.

2020-10-01 15:17 UTC, merged

2020-10-01 15:18 UTC, ammarfaizi2 commented
Merged, thanks for the review.